// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetApiKey() {
  return window['go']['main']['App']['GetApiKey']();
}

export function GetImages(arg1) {
  return window['go']['main']['App']['GetImages'](arg1);
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function OpenUrlSystemBrowser(arg1) {
  return window['go']['main']['App']['OpenUrlSystemBrowser'](arg1);
}

export function SetApiKey(arg1) {
  return window['go']['main']['App']['SetApiKey'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetWallpaper(arg1) {
  return window['go']['main']['App']['SetWallpaper'](arg1);
}
