// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetApiKey():Promise<string>;

export function GetImages(arg1:main.QueryOptions):Promise<main.QueryResponse>;

export function GetTheme():Promise<string>;

export function OpenUrlSystemBrowser(arg1:string):Promise<void>;

export function SetApiKey(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetWallpaper(arg1:string):Promise<void>;
