// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetImages(arg1:main.QueryOptions):Promise<main.QueryResponse>;

export function Greet(arg1:string):Promise<string>;
